/*
FUNDACION KINAL
CENTRO EDUCATIVO TECNICO LARELEORAL KINAL
PEROTO EN ELECTRONICA
QUINTO PERITO
SECCION: A
CURSO: TALLER DE ELECTRONICA DIGITAL Y REPARACION DE COMPUTADORAS
ALUMNOS: ANGELLO GARELERIEL MANSILLA DIEGUEZ y PABLO DAVID HERNANDEZ AJIATAZ
CARNETS: 2022380 y 2022472
PRACTICA 4 DISEÑO DE FIRMWARE
*/

#include <LiquidCrystal.h>

LiquidCrystal ANGELLO(7, 6, 5, 4, 3, 2);

void setup()
{
ANGELLO.begin(16, 2); 
  
 ANGELLO.print("Angello Mansilla");
 ANGELLO.setCursor(0,1);
 ANGELLO.print("2022380");
}

void loop()
{
  
}
